const Loader = () => {
  return (
    <svg
      id="Layer_1"
      x="0px"
      y="0px"
      width="128px"
      height="128px"
      viewBox="0 0 128 128"
      enableBackground="new 0 0 128 128"
      className="grow self-center"
      aria-live="assertive"
      aria-atomic="true"
      aria-hidden="false"
    >
      <title>Loading</title>
      <rect
        id="_x30_1"
        x="10"
        y="93"
        fill="#254A5B"
        width="25"
        height="25"
        className="animate-[loading_1s_ease-out_600ms_infinite]"
      />
      <rect
        id="_x30_2"
        x="37.8"
        y="65.3"
        fill="#254A5B"
        width="25"
        height="25"
        className="animate-[loading_1s_ease-out_600ms_infinite]"
      />
      <rect
        id="_x30_3"
        x="37.7"
        y="93"
        fill="#254A5B"
        width="25"
        height="25"
        className="animate-[loading_1s_ease-out_400ms_infinite]"
      />
      <rect
        id="_x30_4"
        x="65.4"
        y="37.8"
        fill="#254A5B"
        width="25"
        height="25"
        className="animate-[loading_1s_ease-out_600ms_infinite]"
      />
      <rect
        id="_x30_5"
        x="65.4"
        y="65.4"
        fill="#254A5B"
        width="25"
        height="25"
        className="animate-[loading_1s_ease-out_400ms_infinite]"
      />
      <rect
        id="_x30_6"
        x="65.3"
        y="93"
        fill="#254A5B"
        width="25"
        height="25"
        className="animate-[loading_1s_ease-out_200ms_infinite]"
      />
      <rect
        id="_x30_7"
        x="93"
        y="10"
        fill="#254A5B"
        width="25"
        height="25"
        className="animate-[loading_1s_ease-out_600ms_infinite]"
      />
      <rect
        id="_x30_8"
        x="93"
        y="37.7"
        fill="#254A5B"
        width="25"
        height="25"
        className="animate-[loading_1s_ease-out_400ms_infinite]"
      />
      <rect
        id="_x30_9"
        x="93"
        y="65.3"
        fill="#254A5B"
        width="25"
        height="25"
        className="animate-[loading_1s_ease-out_200ms_infinite]"
      />
      <rect
        id="_x31_0"
        x="93"
        y="93"
        fill="#254A5B"
        width="25"
        height="25"
        className="animate-[loading_1s_ease-out_infinite]"
      />
    </svg>
  );
};

export default Loader;
